# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0de493b683abb81c6490649df86efd1ec542b86f18cfdb7a24d06620135bee4bf5277c68da3812d11394bb6cc6001745ba9b9a605d95ad0c7b71c0fae8c7772

test:
  secret_key_base: e3b5cb0c497ad6853aa34f2755f79a113ee2b924d951141183fa31e882a9a9098d4728b0b25174d2e54e325d42f640fe0b603c12eaa86c722520dae7169e2eaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
